export const skills = [
    "Java",
    "Python",
    "JavaScript",
    "Typescript",
    "C#",
    "HTML",
    "CSS",
    "Node.js",
    "Next.js",
    "ReactJS",
    "SQL",
    "PL/SQL",
    "MongoDB",
    "AI",
    "Machine Learning",
    "Data preprocessing",
    "Data extraction",
    "Data transformation",
    "Data cleaning",
    "Big Data tools",
    "Distributed learning",
    "Hadoop",
    "YARN",
    "Apache Spark",
    "Neural network models",
    "Keras",
    "TensorFlow",
    "Data reporting",
    "Data visualization",
    "Automation tools",
    "SDLC",
    "Full-stack web development",
    "Android app development",
    "Cloud computing platforms",
    "Azure",
    "GitHub",
    "Jira",
  ];